### ISSUE TITLE
Proje Temeli ve Mimarisi

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#1]
Bu projeyi React ile başlatmak için create-react-app mi kullanmayı düşünüyoruz, yoksa Next.js gibi bir framework mü tercih ediyoruz?

**Comment by Kev-BB** [comment]
Next.js’in çok yönlülüğü ve React’in geliştiricileri tarafından önerilen framework olması sebebiyle projemizde Next.js kullanmaya karar verdik.
