### ISSUE TITLE
CSS Kütüphaneleri ve Stil Yönetimi:

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#2]
Proje için kullanılacak CSS kütüphanesini belirlerken nelere öncelik vereceğiz? (uyumluluk, özelleştirilebilirlik, hafiflik, vs.)

Projeyi hangi cihazlarda kullanmayı hedefliyoruz? (Masaüstü, tablet, mobil)

Responsive tasarım ve mobil uyumluluk için hangi stratejileri benimsemeliyiz?

**Comment by irfanbariss** [comment]
Stillerde ortak bir yapı kullanmak adına günümüzde de çokça kullanılan Material-UI kullanmaya karar verdik.
