### ISSUE TITLE
State Yönetimi Stratejisi

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#3]
Büyük ve karmaşık uygulama state'lerini nasıl yönetmeyi planlıyoruz?

Proje boyunca verileri nasıl yönetmeyi planlıyoruz? Sadece React state'ini mi kullanmalı, yoksa React Context API veya global state yönetimi için Redux gibi bir  kütüphane mi eklemeliyiz?

Redux gibi bir state yönetim kütüphanesi eklenmesi durumunda, hangi durumların global state'e dahil edilmesi gerektiğini nasıl belirleyeceğiz?

**Comment by dncmusa** [comment]
State yönetimi için React Context API kullanmaya karar verdik.
