### ISSUE TITLE
Routing Stratejisi ve Sayfa Yönlendirmeleri

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#4]
Sayfa yönlendirmeleri için react-router-dom kullanmalı mıyız, yoksa Next.js'in dahili routing özelliklerinden faydalanmalı mıyız?

Dynamic route'lar veya nested route'lar gibi özel durumlar için nasıl bir strateji izlemeliyiz?

**Comment by seraykursunel** [comment]
Projenin sadece tek sayfadan oluşacağını öngördüğümüz için Next.js'in yerleşik yönlendirme özelliklerini veya react-router-dom'u kullanmak gerekli değildir.
