### ISSUE TITLE
API İletişimi ve Veri Yönetimi

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#5]
Projede hangi API iletişim yöntemini kullanmalıyız? (Fetch API, Axios, vs.)

**Comment by bseymad** [comment]
API kullanımı, mevcut diğer çözümlere göre önemli avantajlar sağlamayacaktır. Proje içeriği esas olarak dahili veriler ve işlevlerden oluşmaktadır. Bu sebeple projemizde bir API kullanmamaya karar verdik.
