### ISSUE TITLE
Code Style ve Standartlar

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#6]
Proje boyunca tutarlı bir code style ve standartlar kümesi belirlemek adına hangi araçları kullanmalıyız? (Linting, Prettier, EditorConfig, vs.)

Kod incelemeleri ve pull requestler için nasıl bir süreç izlemeliyiz?

**Comment by mahmetdursun** [comment]
Projemizde tutarlı bir şekilde kod yazmak ve otomatik biçimlendirmelerden yararlanmak için Prettier kullanmaya karar verdik.
