### ISSUE TITLE
Veritabanı ve Veri Yönetimi

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#7]
Proje için  bir veritabanı kullanmayı planlıyor muyuz? 

Veri yönetimi, CRUD işlemleri ve veritabanı güncellemeleri konusunda nasıl bir strateji benimsemeliyiz?

**Comment by ogiboy** [comment]
Projenin gereksinimlerini analiz ettik ve özel bir veritabanına ihtiyaç duymadan hedeflerimize ulaşabileceğimize inanıyoruz. Bu kararın nedenlerinden biri projenin basitliğidir. Projemiz ağırlıklı olarak statik sayfalardan ve veritabanı olmadan kolayca sürdürülebilecek içeriklerden oluşmaktadır.
