### ISSUE TITLE
Kullanıcı Yetkilendirmesi ve Kimlik Doğrulama

### ISSUE THREAD

**Issue by muratakdag** [BilgeAdam-Academy-Students-3507/bilgeadam-students#8]
Kullanıcıların yetkilendirilmesi ve kimlik doğrulama için stratejiye ihtiyacımız var mı? (JWT, OAuth, vs.)

Var ise hangi kullanıcı rollerini tanımlamalı ve nasıl yönetmeliyiz?

**Comment by hakankgn** [comment]
Şu an için projemizin ihtiyaçları doğrultusunda kullanıcı yetkilendirme ve kimlik doğrulama stratejisi belirlemeye gerek görmüyoruz. Bu konuda şu anda bir planlama veya analiz yapmamız gerekmeyecek.
